# Generated by Django 4.0.3 on 2022-03-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodshepard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
